AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'db/schema.rb'
    - 'config/routes.rb'
    - 'config/puma.rb'

Metrics/LineLength:
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'config/**/*'
    - 'db/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 20

Style/Documentation:
  Exclude:
    - 'db/**/*'
    - 'app/models/**/*'

Style/ExtraSpacing:
  Exclude:
    - 'Gemfile'

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/ClassAndModuleChildren:
  Exclude:
    - 'app/controllers/**/*'

Style/SpaceBeforeFirstArg:
  Exclude:
    - 'app/views/**/*'

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/SignalException:
  Exclude:
    - 'app/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false
