version: '2'
services:
  db:
    image: postgres:9.5.3
    ports:
      - "5432:5432"

  app:
    build: .
    command: bin/rails server --port 3000 --binding 0.0.0.0
    environment:
      - DB_PORT_5432_TCP_ADDR=db
      - DB_PORT_5432_TCP_PORT=5432
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - .:/app
